[package]
name = "zmq"
version = "0.1.0"
authors = ["Alec Matusis <matusis@matusis.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zmq = "0.9"
hex = "0.4"

[features]
vendored-zmq = ['zmq/vendored']
